### ISSUE TITLE
Digital communications project, minor bug :)

### ISSUE THREAD

**Issue by Deloss22** [skaftanis/university_projects#1]
On file **erotima5B.m** from the digital communications project, in line **30** should be `for i=1:length(diffSymbols)` instead of `for i=1:26` because the alphabet produced from the file "kwords.txt" is 39 symbols long, not 26, thus causing the average code length to be 68 instead of 71 bits long.

Best Regards.

**Comment by skaftanis** [comment]
You are right! Thanks!
